# Configuración para entrenamiento con 10% del AISegment Dataset
# Dataset: ~3,400 imágenes (10% de 34,425)
# Útil para validación de hiperparámetros antes de full training

experiment:
  name: "AISegment 10% Dataset - ResNet-50"
  description: "Entrenamiento con 10% del AISegment Dataset para validación rápida"
  mode: "debug"

model:
  architecture: "resnet50"
  image_size: 384
  use_pretrained: true
  use_attention: true

dataset:
  type: "aisegment"
  root: "datasets/AISegment"

  # Descarga automática con kagglehub
  auto_download: true
  kaggle_dataset_id: "laurentmih/aisegmentcom-matting-human-datasets"

  # Split train/val
  train_val_split: 0.8

  # Usar 10% del dataset (~3,400 imágenes)
  sampling:
    enabled: true
    mode: "percentage"
    percentage: 0.1      # 10% del dataset
    strategy: "random"
    random_seed: 42

training:
  num_epochs: 50       # Menos epochs que full
  batch_size: 16
  learning_rate: 0.0001
  weight_decay: 0.000001
  num_workers: 8
  pin_memory: true
  drop_last: true
  gradient_clip_max_norm: 0.5
  mixed_precision: true

  scheduler:
    type: "cosine_annealing"
    T_0: 8
    T_mult: 2

  loss_weights:
    alpha: 1.0
    beta: 1.0
    gamma: 0.5
    delta: 0.3

validation:
  frequency: 1
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.0001
  target_metrics:
    iou: 0.83
    dice: 0.88
    pixel_accuracy: 0.93

checkpoints:
  save_best: true
  save_last: true
  save_every_n_epochs: 5
  checkpoint_dir: "checkpoints/aisegment_10pct"

logging:
  log_every_n_batches: 10
  save_plots: true

augmentation:
  train:
    horizontal_flip: 0.5
    random_rotate90: 0.3
    shift_scale_rotate:
      enabled: true
      shift_limit: 0.1
      scale_limit: 0.2
      rotate_limit: 15
      p: 0.5
    brightness_contrast:
      enabled: true
      brightness_limit: 0.2
      contrast_limit: 0.2
      p: 0.5
    hue_saturation_value:
      enabled: true
      hue_shift_limit: 10
      sat_shift_limit: 20
      val_shift_limit: 10
      p: 0.3
    gaussian_blur:
      enabled: true
      blur_limit: 3
      p: 0.2
