# Configuraci칩n para entrenamiento completo con AISegment Matting Human Dataset
# Dataset: 34,425 im치genes de retratos de medio cuerpo con matting masks
# Fuente: https://www.kaggle.com/datasets/laurentmih/aisegmentcom-matting-human-datasets

experiment:
  name: "AISegment Full Training - ResNet-50"
  description: "Entrenamiento completo con AISegment Matting Human Dataset (34,425 im치genes)"
  mode: "production"

model:
  architecture: "resnet50"
  image_size: 384
  use_pretrained: true
  use_attention: true

dataset:
  type: "aisegment"
  root: "datasets/AISegment"

  # Descarga autom치tica con kagglehub
  auto_download: true
  kaggle_dataset_id: "laurentmih/aisegmentcom-matting-human-datasets"

  # Split train/val
  train_val_split: 0.8  # 27,540 train, 6,885 val

  # Sin muestreo - dataset completo
  sampling:
    enabled: false
    mode: "full"

training:
  num_epochs: 100
  batch_size: 16
  learning_rate: 0.0001
  weight_decay: 0.000001
  num_workers: 8
  pin_memory: true
  drop_last: true
  gradient_clip_max_norm: 0.5
  mixed_precision: true

  scheduler:
    type: "cosine_annealing"
    T_0: 10
    T_mult: 2

  loss_weights:
    alpha: 1.0   # BCE
    beta: 1.0    # Dice
    gamma: 0.5   # Perceptual
    delta: 0.3   # Edge

validation:
  frequency: 1
  early_stopping:
    enabled: true
    patience: 15
    min_delta: 0.0001
  target_metrics:
    iou: 0.85
    dice: 0.90
    pixel_accuracy: 0.95

checkpoints:
  save_best: true
  save_last: true
  save_every_n_epochs: 5
  checkpoint_dir: "checkpoints/aisegment_resnet50"

logging:
  log_every_n_batches: 10
  save_plots: true
  plot_dpi: 300

augmentation:
  train:
    horizontal_flip: 0.5
    random_rotate90: 0.3
    shift_scale_rotate:
      enabled: true
      shift_limit: 0.1
      scale_limit: 0.2
      rotate_limit: 15
      p: 0.5
    brightness_contrast:
      enabled: true
      brightness_limit: 0.2
      contrast_limit: 0.2
      p: 0.5
    hue_saturation_value:
      enabled: true
      hue_shift_limit: 10
      sat_shift_limit: 20
      val_shift_limit: 10
      p: 0.3
    gaussian_blur:
      enabled: true
      blur_limit: 3
      p: 0.2
